Postgres changed from single connection to pool
Shopify/shopify-app-js pull request #76
Opened 2022-12-24 05:50 UTC by markustripp

### Overview/summary

The Postgres SessionStorage interface establishes a single connection to the Postgres database. When this connection died for some reason, the entire Shopify app does not work anymore. There is no mechanism for connection management and reconnection. I had this problem with some of my Shopify apps that suddenly stopped working. Sometimes after a few hours, sometimes after a couple of days. Fun to debug. I deploy my Shopify apps to fly.io with my database at Supabase. The reason why the connection gets closed is somewhere in the infrastructure between fly.io and Supabase. Hard to say. Anyway, using the connection pool from the pg module guarantees a reliable connection between the app and the database.

### Fix

In my PR, I simply replaced the pg.Client with the Pool from the pg module which manages the connections. As the Pool class does not have access to the database variable, I have to use the connection string parser from the pg module and store the database in a separate variable. Loom tests pass.

## Type of change

- [ ] Patch: Bug (non-breaking change which fixes an issue)
- [x] Minor: New feature (non-breaking change which adds functionality)
- [ ] Major: Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] I have added a changelog entry, prefixed by the type of change noted above
- [x] I have added/updated tests for this change
- [ ] I have documented new APIs/updated the documentation for modified APIs (for public APIs)

2023-01-15 23:44 UTC, SeanMythen commented
I'm running into this same issue myself, where after a few hours of inactivity, my app will crash due to the database not being connected anymore.

My error typically looks something like this: 
```
node:events:491
throw er; // Unhandled 'error' event
^
Error: Connection terminated unexpectedly
at Connection.<anonymous> (/app/node_modules/pg/lib/client.js:132:73)
```

After doing research I'm not sure if it has anything to do with a deeper error handling issue within the pg library
https://github.com/brianc/node-postgres/issues/1611#issuecomment-558566873

Has using Pool fixed the issue entirely for you?

2023-01-16 23:56 UTC, SeanMythen commented
How can we get this merged into the main branch? Is all that is needed for a further review is to sign the CLA?

2023-01-18 18:04 UTC, SeanMythen commented
@conspireagency is this an issue you face too using the postgres adapter?

2023-01-18 19:51 UTC, cquemin requested changes
Thanks a lot for your contribution. I think this is a great improvement.

However since we offer many session storage implementations, would you be able to make the same changes for the other implementation where relevant? Otherwise we would have inconsistency between the implementations.
 
After you run the tests locally with commands like: `yarn test packages/shopify-app-session-storage-postgresql`. You will need to add some change logs. We are using `changeset` on this repo so you will need to run `yarn changeset` and follow the instructions on the screen. After that, don't forget to push the modified/generated file.

2023-01-18 19:51 UTC, cquemin commented on packages/shopify-app-session-storage-postgresql/src/postgresql.ts
> +    this.database = config.database || 'postgres';
I would suggest to use the right side of your assignment straight where `this.database` is used L145. I think it increases readability and reduces ever so slightly the cognitive load.

2023-01-26 05:18 UTC, closed without merging